[programs.localnet]
ratio = "6cDMc7baVfghT4sUx1t3sEfohxXyj4XwDr8pbarQfz1z"

[clusters.localnet]
ratio = "6cDMc7baVfghT4sUx1t3sEfohxXyj4XwDr8pbarQfz1z"

[provider]
cluster = "localnet"
wallet = "/Users/matthias/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"