[programs.localnet]
ratio = "6cDMc7baVfghT4sUx1t3sEfohxXyj4XwDr8pbarQfz1z"
mint_and_deposit = "9AWyK1cbjJxP5HLctXeiG1ZHRkZo7sUiy7km7SCtjG9G"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copyIdl = "node copy_idl.js"
